services:
  azurite:
    container_name: sdksamples-azurite
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "40000:10000"
      - "40001:10001"
      - "40002:10002"
    volumes:
      - go_azurite_data:/data
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --tableHost 0.0.0.0 --tablePort 10002"

  cosmos:
    container_name: sdksamples-cosmos
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    ports:
      - "8081:8081"
      - "1234:1234"
    environment:
      - PROTOCOL=http
    volumes:
      - go_cosmos_data:/data

  servicebus-emulator:
    container_name: sdksamples-servicebus
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - ./config/servicebus-config.json:/ServiceBus_Emulator/ConfigFiles/Config.json
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: sdksamples-sqledge
      MSSQL_SA_PASSWORD: "s4z7Oqr61egl3"
      ACCEPT_EULA: Y
    depends_on:
      - sqledge
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
  sqledge:
    container_name: sdksamples-sqledge
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    networks:
      sb-emulator:
        aliases:
          - "sqledge"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "s4z7Oqr61egl3"
networks:
  sb-emulator:


volumes:
  go_azurite_data:
  go_cosmos_data:
